from .bordes import *
from .hough import *
from .suavizado import *
from .morfologia import *
from .segmentacion import *
from .mejora import *
from .frecuencia import *
from .color import *
from .geometricos import *
from .segmentacion_avanzada import *
from .gimp import *
from .extendidos import *
